# Input Configuration

[keyboard]
move_up = "Z"
move_down = "S"
move_left = "Q"
move_right = "D"
pause = "Escape"
confirm = "Return"
cancel = "BackSpace"

[controller]
enabled = true
deadzone = 20.0
sensitivity = 100.0

[controller.buttons]
move_up = 3     # Triangle/Y button
move_down = 1   # Circle/B button
move_left = 2   # Square/X button
move_right = 0  # X/A button
pause = 7       # Start button
confirm = 4     # L1 button
cancel = 5      # R1 button

[controller.axes]
horizontal = "X"  # Left stick X-axis
vertical = "Y"    # Left stick Y-axis
