[window]
width = 800
height = 600
title = "SFML Game"

[player]
speed = 200.0
size = 32.0

[debug]
level = "debug"

[controls]
# Keyboard bindings (using SFML key codes)
move_up = "Z"
move_down = "S"
move_left = "Q"
move_right = "D"
pause = "Escape"
confirm = "Return"
cancel = "BackSpace"

# Controller settings
controller_enabled = true
controller_deadzone = 20.0  # Joystick deadzone (0-100) for analog stick movement
controller_sensitivity = 100.0  # Joystick sensitivity for analog stick movement
# Note: Analog stick (X/Y axes) automatically mapped for movement in addition to buttons

# Controller button mappings (using SFML joystick button indices)
controller_move_up = 3     # Usually Triangle/Y button
controller_move_down = 1   # Usually Circle/B button
controller_move_left = 2   # Usually Square/X button
controller_move_right = 0  # Usually X/A button
controller_pause = 7      # Usually Start button
controller_confirm = 4    # Usually L1 button
controller_cancel = 5     # Usually R1 button

[audio]
# Global volume settings (0-100)
master_volume = 100.0
music_volume = 80.0
sound_volume = 100.0

# Sound effects configuration
[audio.sounds]
player_move = { path = "assets/audio/sfx/player_move.ogg", volume = 100.0, min_distance = 1.0, attenuation = 1.0 }
player_collision = { path = "assets/audio/sfx/player_collision.ogg", volume = 100.0, min_distance = 1.0, attenuation = 1.0 }
enemy_collision = { path = "assets/audio/sfx/enemy_collision.ogg", volume = 100.0, min_distance = 1.0, attenuation = 1.0 }

# Music configuration
[audio.music]
main_theme = { path = "assets/audio/music/main_theme.ogg", volume = 80.0, looping = true }
battle_theme = { path = "assets/audio/music/battle_theme.ogg", volume = 80.0, looping = true }
