[window]
width = 800
height = 600
title = "SFML Game"

[player]
speed = 200.0
size = 32.0

[debug]
level = "debug"

[controller]
enabled = true
deadzone = 20.0  # Joystick deadzone (0-100) for analog stick movement
sensitivity = 100.0  # Joystick sensitivity for analog stick movement

[actions]

[actions.MoveUp]
keyboard = ["Z", "Up"]
mouse = []
controller = ["LeftStickUp"]

[actions.MoveDown]
keyboard = ["S", "Down"]
mouse = []
controller = ["LeftStickDown"]

[actions.MoveLeft]
keyboard = ["Q", "Left"]
mouse = []
controller = ["LeftStickLeft"]

[actions.MoveRight]
keyboard = ["D", "Right"]
mouse = []
controller = ["LeftStickRight"]

[actions.Pause]
keyboard = ["Escape"]
mouse = []
controller = ["Start"]

[actions.Confirm]
keyboard = ["Return"]
mouse = ["LeftButton"]
controller = ["A"]

[actions.Cancel]
keyboard = ["BackSpace"]
mouse = ["RightButton"]
controller = ["B"]

[actions.Fire]
keyboard = ["Space"]
mouse = ["LeftButton"]
controller = ["RB"]
