name: CI Cross-Platform Build

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4.1.2
        with:
          path: |
            build/_deps
            ~/.cache/ccache
          key: ${{ runner.os }}-deps-${{ hashFiles('cmake/dependencies.cmake') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            g++ \
            build-essential \
            cmake \
            libx11-dev \
            libgl1-mesa-dev \
            libudev-dev \
            libopenal-dev \
            libvorbis-dev \
            libflac-dev \
            libfreetype-dev \
            xorg-dev \
            libogg-dev \
            xvfb

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Run Tests with Virtual Display
        run: |
          cd build
          xvfb-run --auto-servernum ./sfml_game --test-mode

  build-and-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: llvm/actions/install-ninja@main

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.25.0"

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"
          cmake --build . --config Debug

      - name: Setup Virtual Display
        shell: powershell
        run: |
          # Use RDP Session for headless operation
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # Set display settings
          $env:DISPLAY=":0"

      - name: Run Tests
        shell: cmd
        run: |
          cd build\Debug
          copy ..\_deps\sfml-build\lib\Debug\*.dll .
          copy ..\_deps\spdlog-build\Debug\*.dll .
          copy "C:\Program Files (x86)\OpenAL 1.1 SDK\libs\Win64\OpenAL32.dll" .
          .\sfml_game.exe --test-mode
