name: CI Cross-Platform Build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

jobs:
  build-and-test-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4.1.2
        with:
          path: |
            build/_deps
            ~/.cache/ccache
          key: ${{ runner.os }}-deps-${{ hashFiles('cmake/dependencies.cmake') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libx11-dev \
            libgl1-mesa-dev \
            libudev-dev \
            libopenal-dev \
            libvorbis-dev \
            libflac-dev \
            libfreetype-dev \
            xorg-dev \
            libogg-dev \
            xvfb

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Run Tests with Virtual Display
        run: |
          cd build
          xvfb-run --auto-servernum ./sfml_game --test-mode

  build-and-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache Dependencies
        uses: actions/cache@v4.1.2
        with:
          path: build\_deps
          key: ${{ runner.os }}-deps-${{ hashFiles('cmake/dependencies.cmake') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.25.0"

      - name: Build
        shell: powershell
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PACKAGE_ZIP=ON
          cmake --build build --config Release 

      - name: Setup Virtual Display
        shell: powershell
        run: |
          # Use RDP Session for headless operation
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # Set display settings
          $env:DISPLAY=":0"

      - name: Run Tests
        shell: cmd
        run: |
          cd build
          copy "C:\Program Files (x86)\OpenAL 1.1 SDK\libs\Win64\OpenAL32.dll" .
          .\sfml_game.exe --test-mode
