name: Scheduled check of available libs updates

on: [workflow_dispatch, push]

defaults:
  run:
    shell: bash
    working-directory: ./tools/dependency_checker

jobs:
  periodic-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create PRs
      pull-requests: write  # Needed to create PRs
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the full history for diffing

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake

      - name: Build & execute
        run: |
          ./build.sh
          ./build/dependency_checker --dependencies-file ../../cmake/dependencies.cmake       

      - name: Check if any dependencies have been updated
        id: task
        run: |
          if [[ $(git status | grep modified | xargs | wc -c) -gt 0 ]]; then
            echo "update=true" >> $GITHUB_ENV
          else
            echo "update=false" >> $GITHUB_ENV
          fi

      - name: Update Files If Needed
        if: env.update == 'true'
        run: |
          # Modify files as needed
          echo "Updating files..."